### ISSUE TITLE
HeaderCheck - Stack trace suppress - SBT Multi module project

### ISSUE THREAD

**Issue by francescofrontera** [sbt/sbt-header#114]
Hi,
I'm trying to use Sbt-Header with a sbt multimodule project, but i'm having  a `java.lang.RuntimeException: There are files without headers!` but the files(.scala,.xml) actually contains header.
The stacktrace is:
```at scala.sys.package$.error(package.scala:27)
	at de.heikoseeberger.sbtheader.HeaderPlugin$.de$heikoseeberger$sbtheader$HeaderPlugin$$checkHeadersTask(HeaderPlugin.scala:179)
	at de.heikoseeberger.sbtheader.HeaderPlugin$$anonfun$de$heikoseeberger$sbtheader$HeaderPlugin$$toBeScopedSettings$4.apply(HeaderPlugin.scala:115)
	at de.heikoseeberger.sbtheader.HeaderPlugin$$anonfun$de$heikoseeberger$sbtheader$HeaderPlugin$$toBeScopedSettings$4.apply(HeaderPlugin.scala:115)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)```
any idea? thanks.

**Comment by britter** [comment]
Hi!

Are you using the latest version of sbt-header (2.0.0)? We had a bug in C++ comment style before 2.0.0.

If you run headerCreate, does it change your files? Maybe it adds an empty line between the header and the file contents.

I'm currently on vacation so I can not really assist until June.

**Comment by britter** [comment]
@francescofrontera we need more input to analyze this problem.

**Comment by francescofrontera** [comment]
@britter The problems was due to the lack of spaces at the beginning of the  custom header.
Thanks for your supports.
