### ISSUE TITLE
[error] (coreJVM/compile:createHeaders) java.nio.charset.UnmappableCharacterException: Input length = 1

### ISSUE THREAD

**Issue by nishanpatel** [sbt/sbt-header#160]
Hi Team,

I am using below project to run in my local machine with following configurations, Windows 10, Scala version 2.12.6, java version 1.8.0_161, SBT version 1.2.1 and IntelliJ IDEA.

[Project](https://github.com/scala-exercises/scala-exercises
)

I tried following options,

- Tried with all version of SBT(1.2.3, 1.0.x and 0.13.x)

- Tried with scalacOptions ++= Seq("-encoding, UTF-8")

I have tried with all possible options but  I am still facing the same issue. 

java.nio.charset.UnmappableCharacterException: Input length = 1
        at java.nio.charset.CoderResult.throwException(CoderResult.java:282)
        at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:339)
        at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
        at java.io.InputStreamReader.read(InputStreamReader.java:184)
        at java.io.BufferedReader.fill(BufferedReader.java:161)
        at java.io.BufferedReader.read(BufferedReader.java:182)
        at scala.io.BufferedSource$$anonfun$iter$1$$anonfun$apply$mcI$sp$1.apply$mcI$sp(BufferedSource.scala:38)
        at scala.io.Codec.wrap(Codec.scala:68)
        at scala.io.BufferedSource$$anonfun$iter$1.apply(BufferedSource.scala:38)
        at scala.io.BufferedSource$$anonfun$iter$1.apply(BufferedSource.scala:38)
        at scala.collection.Iterator$$anon$9.next(Iterator.scala:162)
        at scala.collection.Iterator$$anon$17.hasNext(Iterator.scala:511)
        at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:327)
        at scala.io.Source.hasNext(Source.scala:226)
        at scala.collection.Iterator$class.foreach(Iterator.scala:727)
        at scala.io.Source.foreach(Source.scala:178)
        at scala.collection.TraversableOnce$class.addString(TraversableOnce.scala:320)
        at scala.io.Source.addString(Source.scala:178)
        at scala.collection.TraversableOnce$class.mkString(TraversableOnce.scala:286)
        at scala.io.Source.mkString(Source.scala:178)
        at scala.collection.TraversableOnce$class.mkString(TraversableOnce.scala:288)
        at scala.io.Source.mkString(Source.scala:178)
        at scala.collection.TraversableOnce$class.mkString(TraversableOnce.scala:290)
        at scala.io.Source.mkString(Source.scala:178)
        at de.heikoseeberger.sbtheader.HeaderCreator.<init>(HeaderCreator.scala:30)
        at de.heikoseeberger.sbtheader.HeaderCreator$.apply(HeaderCreator.scala:65)
        at de.heikoseeberger.sbtheader.HeaderPlugin$.de$heikoseeberger$sbtheader$HeaderPlugin$$createHeader(HeaderPlugin.scala:136)
        at de.heikoseeberger.sbtheader.HeaderPlugin$$anonfun$1$$anonfun$apply$2.apply(HeaderPlugin.scala:127)
        at de.heikoseeberger.sbtheader.HeaderPlugin$$anonfun$1$$anonfun$apply$2.apply(HeaderPlugin.scala:127)
        at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:251)
        at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:251)
        at scala.collection.immutable.List.foreach(List.scala:318)
        at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:251)
        at scala.collection.AbstractTraversable.flatMap(Traversable.scala:105)
        at de.heikoseeberger.sbtheader.HeaderPlugin$$anonfun$1.apply(HeaderPlugin.scala:127)
        at de.heikoseeberger.sbtheader.HeaderPlugin$$anonfun$1.apply(HeaderPlugin.scala:127)
        at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:251)
        at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:251)
        at scala.collection.immutable.List.foreach(List.scala:318)
        at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:251)
        at scala.collection.AbstractTraversable.flatMap(Traversable.scala:105)
        at de.heikoseeberger.sbtheader.HeaderPlugin$.de$heikoseeberger$sbtheader$HeaderPlugin$$createHeadersTask(HeaderPlugin.scala:127)
        at de.heikoseeberger.sbtheader.HeaderPlugin$$anonfun$toBeScopedSettings$3.apply(HeaderPlugin.scala:103)
        at de.heikoseeberger.sbtheader.HeaderPlugin$$anonfun$toBeScopedSettings$3.apply(HeaderPlugin.scala:103)
        at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
        at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
        at sbt.std.Transform$$anon$4.work(System.scala:63)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
        at sbt.Execute.work(Execute.scala:237)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
        at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
        at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
[error] (coreJVM/compile:createHeaders) java.nio.charset.UnmappableCharacterException: Input length = 1
[error] Total time: 1 s, completed 20-Sep-2018 20:25:54

**Comment by nishanpatel** [comment]
Thanks @britter but no idea and looks like it is encoding issue.

**Comment by nishanpatel** [comment]
The work around works for me. 

GOTO SBT setup --> conf --> Edit sbtconfig.txt --> added -Dfile.encoding=UTF8

Happy to close the issue.

**Comment by mikereiche** [comment]
I hit this with the special double quotes in comments ( the 66 ... 99 quotes ).  I just replaced them with regular double-quotes.
