### ISSUE TITLE
Document how the sbt-header-test project works

### ISSUE THREAD

**Issue by britter** [sbt/sbt-header#51]
I'm working on a PR for #30 but I have no idea how the test project works. When I start sbt in the sbt-header-test folder I get:

```
[error]
[error]      while compiling: /Users/bene/workspace/projects/sbt-header/src/main/scala/de/heikoseeberger/sbtheader/package.scala
[error]         during phase: jvm
[error]      library version: version 2.10.6
[error]     compiler version: version 2.10.6
[error]   reconstructed args: -language:_ -deprecation -unchecked -classpath /Users/bene/workspace/projects/sbt-header/target/scala-2.10/sbt-0.13/classes:/Users/bene/.sbt/0.13/plugins/target/scala-2.10/sbt-0.13/classes:/Users/bene/.ivy2/cache/scala_2.10/sbt_0.13/de.heikoseeberger/sbt-fresh/jars/sbt-fresh-1.1.0.jar:/Users/bene/.ivy2/cache/org.eclipse.jgit/org.eclipse.jgit/jars/org.eclipse.jgit-4.2.0.201601211800-r.jar:/Users/bene/.ivy2/cache/com.jcraft/jsch/jars/jsch-0.1.53.jar:/Users/bene/.ivy2/cache/com.googlecode.javaewah/JavaEWAH/bundles/JavaEWAH-0.7.9.jar:/Users/bene/.ivy2/cache/org.apache.httpcomponents/httpclient/jars/httpclient-4.3.6.jar:/Users/bene/.ivy2/cache/org.apache.httpcomponents/httpcore/jars/httpcore-4.3.3.jar:/Users/bene/.ivy2/cache/commons-logging/commons-logging/jars/commons-logging-1.1.3.jar:/Users/bene/.ivy2/cache/commons-codec/commons-codec/jars/commons-codec-1.6.jar:/Users/bene/.ivy2/cache/org.slf4j/slf4j-api/jars/slf4j-api-1.7.2.jar:/Users/bene/.ivy2/cache/org.scala-sbt/sbt/jars/sbt-0.13.11.jar:/Users/bene/.ivy2/cache/org.scala-sbt/main/jars/main-0.13.11.jar:/Users/bene/.ivy2/cache/org.scala-sbt/actions/jars/actions-0.13.11.jar:/Users/bene/.ivy2/cache/org.scala-sbt/classpath/jars/classpath-0.13.11.jar:/Users/bene/.sbt/boot/scala-2.10.6/lib/scala-compiler.jar:/Users/bene/.sbt/boot/scala-2.10.6/lib/scala-reflect.jar:/Users/bene/.ivy2/cache/org.scala-sbt/interface/jars/interface-0.13.11.jar:/Users/bene/.ivy2/cache/org.scala-sbt/io/jars/io-0.13.11.jar:/Users/bene/.ivy2/cache/org.scala-sbt/control/jars/control-0.13.11.jar:/Users/bene/.ivy2/cache/org.scala-sbt/launcher-interface/jars/launcher-interface-1.0.0-M1.jar:/Users/bene/.ivy2/cache/org.scala-sbt/completion/jars/completion-0.13.11.jar:/Users/bene/.ivy2/cache/org.scala-sbt/collections/jars/collections-0.13.11.jar:/Users/bene/.ivy2/cache/jline/jline/jars/jline-2.13.jar:/Users/bene/.ivy2/cache/org.fusesource.jansi/jansi/jars/jansi-1.11.jar:/Users/bene/.ivy2/cache/org.scala-sbt/api/jars/api-0.13.11.jar:/Users/bene/.ivy2/cache/org.scala-sbt/classfile/jars/classfile-0.13.11.jar:/Users/bene/.ivy2/cache/org.scala-sbt/logging/jars/logging-0.13.11.jar:/Users/bene/.ivy2/cache/org.scala-sbt/process/jars/process-0.13.11.jar:/Users/bene/.ivy2/cache/org.scala-sbt/compiler-integration/jars/compiler-integration-0.13.11.jar:/Users/bene/.ivy2/cache/org.scala-sbt/incremental-compiler/jars/incremental-compiler-0.13.11.jar:/Users/bene/.ivy2/cache/org.scala-sbt/relation/jars/relation-0.13.11.jar:/Users/bene/.ivy2/cache/org.scala-sbt/compile/jars/compile-0.13.11.jar:/Users/bene/.ivy2/cache/org.scala-sbt/persist/jars/persist-0.13.11.jar:/Users/bene/.ivy2/cache/org.scala-tools.sbinary/sbinary_2.10/jars/sbinary_2.10-0.4.2.jar:/Users/bene/.ivy2/cache/org.scala-sbt/compiler-ivy-integration/jars/compiler-ivy-integration-0.13.11.jar:/Users/bene/.ivy2/cache/org.scala-sbt/ivy/jars/ivy-0.13.11.jar:/Users/bene/.ivy2/cache/org.scala-sbt/cross/jars/cross-0.13.11.jar:/Users/bene/.ivy2/cache/org.scala-sbt.ivy/ivy/jars/ivy-2.3.0-sbt-2cc8d2761242b072cedb0a04cb39435c4fa24f9a.jar:/Users/bene/.ivy2/cache/org.scala-sbt/serialization_2.10/jars/serialization_2.10-0.1.2.jar:/Users/bene/.ivy2/cache/org.scala-lang.modules/scala-pickling_2.10/jars/scala-pickling_2.10-0.10.1.jar:/Users/bene/.ivy2/cache/org.scalamacros/quasiquotes_2.10/jars/quasiquotes_2.10-2.0.1.jar:/Users/bene/.ivy2/cache/org.json4s/json4s-core_2.10/jars/json4s-core_2.10-3.2.10.jar:/Users/bene/.ivy2/cache/org.json4s/json4s-ast_2.10/jars/json4s-ast_2.10-3.2.10.jar:/Users/bene/.ivy2/cache/com.thoughtworks.paranamer/paranamer/jars/paranamer-2.6.jar:/Users/bene/.ivy2/cache/org.spire-math/jawn-parser_2.10/jars/jawn-parser_2.10-0.6.0.jar:/Users/bene/.ivy2/cache/org.spire-math/json4s-support_2.10/jars/json4s-support_2.10-0.6.0.jar:/Users/bene/.ivy2/cache/org.scala-sbt/run/jars/run-0.13.11.jar:/Users/bene/.ivy2/cache/org.scala-sbt/task-system/jars/task-system-0.13.11.jar:/Users/bene/.ivy2/cache/org.scala-sbt/tasks/jars/tasks-0.13.11.jar:/Users/bene/.ivy2/cache/org.scala-sbt/tracking/jars/tracking-0.13.11.jar:/Users/bene/.ivy2/cache/org.scala-sbt/cache/jars/cache-0.13.11.jar:/Users/bene/.ivy2/cache/org.scala-sbt/testing/jars/testing-0.13.11.jar:/Users/bene/.ivy2/cache/org.scala-sbt/test-agent/jars/test-agent-0.13.11.jar:/Users/bene/.ivy2/cache/org.scala-sbt/test-interface/jars/test-interface-1.0.jar:/Users/bene/.ivy2/cache/org.scala-sbt/main-settings/jars/main-settings-0.13.11.jar:/Users/bene/.ivy2/cache/org.scala-sbt/apply-macro/jars/apply-macro-0.13.11.jar:/Users/bene/.ivy2/cache/org.scala-sbt/command/jars/command-0.13.11.jar:/Users/bene/.ivy2/cache/org.scala-sbt/logic/jars/logic-0.13.11.jar:/Users/bene/.ivy2/cache/org.scala-sbt/compiler-interface/jars/compiler-interface-0.13.11.jar -target:jvm-1.7 -bootclasspath /Library/Java/JavaVirtualMachines/jdk1.8.0_91.jdk/Contents/Home/jre/lib/resources.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_91.jdk/Contents/Home/jre/lib/rt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_91.jdk/Contents/Home/jre/lib/sunrsasign.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_91.jdk/Contents/Home/jre/lib/jsse.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_91.jdk/Contents/Home/jre/lib/jce.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_91.jdk/Contents/Home/jre/lib/charsets.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_91.jdk/Contents/Home/jre/lib/jfr.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_91.jdk/Contents/Home/jre/classes:/Users/bene/.sbt/boot/scala-2.10.6/lib/scala-library.jar
[error]
[error]   last tree to typer: Literal(Constant(java.io.File))
[error]               symbol: null
[error]    symbol definition: null
[error]                  tpe: Class(classOf[java.io.File])
[error]        symbol owners:
[error]       context owners: class package$FileOps -> package sbtheader
[error]
[error] == Enclosing template or block ==
[error]
[error] Template( // val <local FileOps>: <notype> in class package$FileOps, tree.tpe=de.heikoseeberger.sbtheader.package$FileOps
[error]   "java.lang.Object" // parents
[error]   ValDef(
[error]     private
[error]     "_"
[error]     <tpt>
[error]     <empty>
[error]   )
[error]   // 6 statements
[error]   ValDef( // private[this] val file: java.io.File in class package$FileOps
[error]     private <local> <paramaccessor> <triedcooking>
[error]     "file "
[error]     <tpt> // tree.tpe=java.io.File
[error]     <empty>
[error]   )
[error]   DefDef( // val file(): java.io.File in class package$FileOps
[error]     <method> <stable> <accessor> <paramaccessor> <triedcooking>
[error]     "file"
[error]     []
[error]     List(Nil)
[error]     <tpt> // tree.tpe=java.io.File
[error]     package$FileOps.this."file " // private[this] val file: java.io.File in class package$FileOps, tree.tpe=java.io.File
[error]   )
[error]   DefDef( // def extension(): Option in class package$FileOps
[error]     <method> <triedcooking>
[error]     "extension"
[error]     []
[error]     List(Nil)
[error]     <tpt> // tree.tpe=Option
[error]     Apply( // final def extension$extension($this: java.io.File): Option in object package$FileOps, tree.tpe=Option
[error]       "de"."heikoseeberger"."sbtheader"."package$FileOps"."extension$extension" // final def extension$extension($this: java.io.File): Option in object package$FileOps, tree.tpe=($this: java.io.File)Option
[error]       Apply( // val file(): java.io.File in class package$FileOps, tree.tpe=java.io.File
[error]         package$FileOps.this."file" // val file(): java.io.File in class package$FileOps, tree.tpe=()java.io.File
[error]         Nil
[error]       )
[error]     )
[error]   )
[error]   DefDef( // override def hashCode(): Int in class package$FileOps
[error]     <method> override <synthetic>
[error]     "hashCode"
[error]     []
[error]     List(Nil)
[error]     <tpt> // tree.tpe=Int
[error]     Apply( // final def hashCode$extension($this: java.io.File): Int in object package$FileOps, tree.tpe=Int
[error]       "de"."heikoseeberger"."sbtheader"."package$FileOps"."hashCode$extension" // final def hashCode$extension($this: java.io.File): Int in object package$FileOps, tree.tpe=($this: java.io.File)Int
[error]       Apply( // val file(): java.io.File in class package$FileOps, tree.tpe=java.io.File
[error]         package$FileOps.this."file" // val file(): java.io.File in class package$FileOps, tree.tpe=()java.io.File
[error]         Nil
[error]       )
[error]     )
[error]   )
[error]   DefDef( // override def equals(x$1: Object): Boolean in class package$FileOps
[error]     <method> override <synthetic>
[error]     "equals"
[error]     []
[error]     // 1 parameter list
[error]     ValDef( // x$1: Object
[error]       <param> <synthetic> <triedcooking>
[error]       "x$1"
[error]       <tpt> // tree.tpe=Object
[error]       <empty>
[error]     )
[error]     <tpt> // tree.tpe=Boolean
[error]     Apply( // final def equals$extension($this: java.io.File,x$1: Object): Boolean in object package$FileOps, tree.tpe=Boolean
[error]       "de"."heikoseeberger"."sbtheader"."package$FileOps"."equals$extension" // final def equals$extension($this: java.io.File,x$1: Object): Boolean in object package$FileOps, tree.tpe=($this: java.io.File, x$1: Object)Boolean
[error]       // 2 arguments
[error]       Apply( // val file(): java.io.File in class package$FileOps, tree.tpe=java.io.File
[error]         package$FileOps.this."file" // val file(): java.io.File in class package$FileOps, tree.tpe=()java.io.File
[error]         Nil
[error]       )
[error]       "x$1" // x$1: Object, tree.tpe=Object
[error]     )
[error]   )
[error]   DefDef( // def <init>(file: java.io.File): de.heikoseeberger.sbtheader.package$FileOps in class package$FileOps
[error]     <method> <triedcooking>
[error]     "<init>"
[error]     []
[error]     // 1 parameter list
[error]     ValDef( // file: java.io.File
[error]       <param> <paramaccessor> <triedcooking>
[error]       "file"
[error]       <tpt> // tree.tpe=java.io.File
[error]       <empty>
[error]     )
[error]     <tpt> // tree.tpe=de.heikoseeberger.sbtheader.package$FileOps
[error]     Block( // tree.tpe=Unit
[error]       // 2 statements
[error]       Assign( // tree.tpe=Unit
[error]         package$FileOps.this."file " // private[this] val file: java.io.File in class package$FileOps, tree.tpe=java.io.File
[error]         "file" // file: java.io.File, tree.tpe=java.io.File
[error]       )
[error]       Apply( // def <init>(): Object in class Object, tree.tpe=Object
[error]         package$FileOps.super."<init>" // def <init>(): Object in class Object, tree.tpe=()Object
[error]         Nil
[error]       )
[error]       ()
[error]     )
[error]   )
[error] )
[error]
[error] == Expanded type of tree ==
[error]
[error] ConstantType(value = Constant(java.io.File))
[error]
[error] uncaught exception during compilation: java.lang.AssertionError
java.lang.AssertionError: assertion failed: List(object package$FileOps, object package$FileOps)
	at scala.reflect.internal.Symbols$Symbol.suchThat(Symbols.scala:1678)
	at scala.reflect.internal.Symbols$ClassSymbol.companionModule0(Symbols.scala:2988)
	at scala.reflect.internal.Symbols$ClassSymbol.companionModule(Symbols.scala:2991)
	at scala.tools.nsc.backend.jvm.GenASM$JPlainBuilder.genClass(GenASM.scala:1371)
	at scala.tools.nsc.backend.jvm.GenASM$AsmPhase.run(GenASM.scala:120)
	at scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1583)
	at scala.tools.nsc.Global$Run.compileUnits(Global.scala:1557)
	at scala.tools.nsc.Global$Run.compileSources(Global.scala:1553)
	at scala.tools.nsc.Global$Run.compile(Global.scala:1662)
	at xsbt.CachedCompiler0.run(CompilerInterface.scala:116)
	at xsbt.CachedCompiler0.run(CompilerInterface.scala:95)
	at xsbt.CompilerInterface.run(CompilerInterface.scala:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sbt.compiler.AnalyzingCompiler.call(AnalyzingCompiler.scala:101)
	at sbt.compiler.AnalyzingCompiler.compile(AnalyzingCompiler.scala:47)
	at sbt.compiler.AnalyzingCompiler.compile(AnalyzingCompiler.scala:41)
	at sbt.compiler.MixedAnalyzingCompiler$$anonfun$compileScala$1$1.apply$mcV$sp(MixedAnalyzingCompiler.scala:50)
	at sbt.compiler.MixedAnalyzingCompiler$$anonfun$compileScala$1$1.apply(MixedAnalyzingCompiler.scala:50)
	at sbt.compiler.MixedAnalyzingCompiler$$anonfun$compileScala$1$1.apply(MixedAnalyzingCompiler.scala:50)
	at sbt.compiler.MixedAnalyzingCompiler.timed(MixedAnalyzingCompiler.scala:74)
	at sbt.compiler.MixedAnalyzingCompiler.compileScala$1(MixedAnalyzingCompiler.scala:49)
	at sbt.compiler.MixedAnalyzingCompiler.compile(MixedAnalyzingCompiler.scala:64)
	at sbt.compiler.IC$$anonfun$compileInternal$1.apply(IncrementalCompiler.scala:160)
	at sbt.compiler.IC$$anonfun$compileInternal$1.apply(IncrementalCompiler.scala:160)
	at sbt.inc.IncrementalCompile$$anonfun$doCompile$1.apply(Compile.scala:66)
	at sbt.inc.IncrementalCompile$$anonfun$doCompile$1.apply(Compile.scala:64)
	at sbt.inc.IncrementalCommon.cycle(IncrementalCommon.scala:32)
	at sbt.inc.Incremental$$anonfun$1.apply(Incremental.scala:68)
	at sbt.inc.Incremental$$anonfun$1.apply(Incremental.scala:67)
	at sbt.inc.Incremental$.manageClassfiles(Incremental.scala:95)
	at sbt.inc.Incremental$.compile(Incremental.scala:67)
	at sbt.inc.IncrementalCompile$.apply(Compile.scala:54)
	at sbt.compiler.IC$.compileInternal(IncrementalCompiler.scala:160)
	at sbt.compiler.IC$.incrementalCompile(IncrementalCompiler.scala:138)
	at sbt.Compiler$.compile(Compiler.scala:152)
	at sbt.Compiler$.compile(Compiler.scala:138)
	at sbt.Defaults$.sbt$Defaults$$compileIncrementalTaskImpl(Defaults.scala:860)
	at sbt.Defaults$$anonfun$compileIncrementalTask$1.apply(Defaults.scala:851)
	at sbt.Defaults$$anonfun$compileIncrementalTask$1.apply(Defaults.scala:849)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[error] ({file:/Users/bene/workspace/projects/sbt-header/}sbtHeader/compile:compileIncremental) java.lang.AssertionError: assertion failed: List(object package$FileOps, object package$FileOps)
```

**Comment by britter** [comment]
I just came across the scripted test framework. Maybe it's a good idea to migrate to setup some tests using that.

**Comment by hseeberger** [comment]
sbt-header-test ist just for playing. Adding scripted tests sounds like a good idea.

**Comment by britter** [comment]
Awesome, I'll have a look into scripted test!
