### ISSUE TITLE
Got error java.lang.NoSuchMethodError: java.nio.file.Files.readAllLines(Ljava/nio/file/Path

### ISSUE THREAD

**Issue by soumyasd** [sbt/sbt-header#8]
I get a java.lang.NoSuchMethodError when I try to run on a project on OS-X.
I'm using 

**SBT**
sbt version 0.13.5. 

**JVM**
java version "1.7.0_45"
Java(TM) SE Runtime Environment (build 1.7.0_45-b18)
Java HotSpot(TM) 64-Bit Server VM (build 24.45-b08, mixed mode)

**Scala** 
scalaVersion := "2.10.4"

`java.lang.NoSuchMethodError: java.nio.file.Files.readAllLines(Ljava/nio/file/Path;)Ljava/util/List;
	at de.heikoseeberger.sbtheader.SbtHeader$.de$heikoseeberger$sbtheader$SbtHeader$$createHeader(SbtHeader.scala:78)
	at de.heikoseeberger.sbtheader.SbtHeader$$anonfun$4$$anonfun$apply$1.apply(SbtHeader.scala:69)
	at de.heikoseeberger.sbtheader.SbtHeader$$anonfun$4$$anonfun$apply$1.apply(SbtHeader.scala:69)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:251)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:251)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:251)
	at scala.collection.AbstractTraversable.flatMap(Traversable.scala:105)
	at de.heikoseeberger.sbtheader.SbtHeader$$anonfun$4.apply(SbtHeader.scala:69)
	at de.heikoseeberger.sbtheader.SbtHeader$$anonfun$4.apply(SbtHeader.scala:69)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:251)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:251)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:251)
	at scala.collection.AbstractTraversable.flatMap(Traversable.scala:105)
	at de.heikoseeberger.sbtheader.SbtHeader$.de$heikoseeberger$sbtheader$SbtHeader$$createHeadersTask(SbtHeader.scala:69)
	at de.heikoseeberger.sbtheader.SbtHeader$$anonfun$toBeScopedSettings$3.apply(SbtHeader.scala:53)
	at de.heikoseeberger.sbtheader.SbtHeader$$anonfun$toBeScopedSettings$3.apply(SbtHeader.scala:53)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:42)
	at sbt.std.Transform$$anon$4.work(System.scala:64)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:237)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:18)
	at sbt.Execute.work(Execute.scala:244)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:237)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:160)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:30)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
[error] (compile:createHeaders) java.lang.NoSuchMethodError: java.nio.file.Files.readAllLines(Ljava/nio/file/Path;)Ljava/util/List;`

**Comment by soumyasd** [comment]
Okay looks like this works on Java 8.

**Comment by soumyasd** [comment]
Will be nice to have support for Java < 8

**Comment by hseeberger** [comment]
Thanks for the heads up. Please give version `1.1.1-a95a88657dc07b8297c0a0390cb6365d994fee26` a try and let me know if it works.

**Comment by soumyasd** [comment]
yeah it works. Thanks.

**Comment by hseeberger** [comment]
Fantastic. 1.1.1 has been released. Enjoy!

**Comment by KMedhansh** [comment]
Hi Team,

I'm getting below error while managing jenkins.

javax.servlet.ServletException: java.lang.NoSuchMethodError: java.nio.file.Files.notExists(Ljava/nio/file/Path;[Ljava/nio/file/LinkOption;)Z

 
What you people are referring to some version 1.1.1? What exactly it is.
